# Generated by Django 5.0.7 on 2024-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy')], max_length=6)),
            ],
        ),
    ]
