# Generated by Django 5.0.7 on 2024-07-20 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role': ['instructor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
