# Generated by Django 5.0.7 on 2024-07-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0003_alter_announcement_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='sender',
            new_name='maker',
        ),
    ]
