# Generated by Django 5.0.6 on 2024-07-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='sameer', max_length=30),
        ),
    ]
